### ISSUE TITLE
componentplan namespace is `u4a-system`, But the pod is deployed under the namespace of the repoisotory

### ISSUE THREAD

**Issue by 0xff-dev** [kubebb/core#105]
componentplan namespace is `u4a-system`, But the pod is deployed under the namespace of the repoisotory.

image: 
```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: cluster-compnent
  namespace: u4a-system
spec:
  approved: true
  name: cluster-component
  version: 0.1.0
  override:
    set:
    # according to https://kubebb.github.io/website/docs/core/get_started#kind%E5%BC%80%E5%8F%91%E9%9B%86%E7%BE%A4
    - ingress-nginx.deployedHost=kubebb-core-worker
  component:
    name: kubebb.cluster-component
    namespace: kubebb-system
```

ingress-nginx won't start because the pod can't be scheduled. the set parameter doesn't seem to be taking effect at the moment.

```yaml
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    kubernetes.io/hostname: kind-worker
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: cluster-component-ingress-nginx
  serviceAccountName: cluster-component-ingress-nginx
  terminationGracePeriodSeconds: 300
  tolerations:
```

pods

```shell
(base) ➜  cluster-component git:(main) ✗ kubectl get po -nkubebb-system
NAME                                                         READY   STATUS    RESTARTS   AGE
cert-manager-56585488fd-75hjn                                1/1     Running   0          19m
cert-manager-cainjector-797b96c765-759qx                     1/1     Running   0          19m
cert-manager-webhook-95fbbccd8-r96g7                         1/1     Running   0          19m
cluster-component-ingress-nginx-controller-bc5c5f9f5-l9hrx   0/1     Pending   0          19m
kubebb-7ddc7b946d-sw6nh                                      1/1     Running   0          23m
```
