### ISSUE TITLE
rbac visualization https://github.com/team-soteria/rback

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#116]

**Comment by 0xff-dev** [comment]
流程：

task:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rback
spec:
  params:
  - name: url
    type: string
  - name: component
    type: string
  - name: version
    type: string
  steps:
    - name: echo
      image: kubebb/component-rbac-gen:v0.0.1
      script: |
        #!/usr/bin/env bash
        curl -LO $(params.url)
        tar -zxvf $(params.component)-$(params.version).tgz
        helm install test --dry-run -oyaml ./$(params.component)|yq '.manifest'| kubectl apply -f - --dry-run=client -ojson| rback > r.dot
        ./run.sh
```

pipeline:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: component-rbac-gen
  annotations:
    tekton.dev/tags: component-rbac-gen
    tekton.dev/displayName: "component-rbac-gen"
    tekton.dev/platforms: "linux/amd64"
  namespace: default
spec:
  description: >-
    convert image to base64
  params:
    - name: COMPONENT_NAME
      description: >-
        component name
    - name: REPOSITORY_NAME
      description: repository name
    - name: VERSION
      description: component version
    - name: URL
      description: url
  tasks:
    - name: rback
      retries: 2
      taskRef:
        name: rback
      params:
        - name: url
          value: $(params.URL)
        - name: component
          value: $(params.COMPONENT_NAME)
        - name: version
          value: $(params.VERSION)
```


pipelinerun:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: component-rbac-gen
  labels:
    description: "A_PipelineRun_For_ChaincodeBuild"
spec:
  serviceAccountName: bbq
  taskRunSpecs:
  - pipelineTaskName: rback
    taskServiceAccountName: bbq
  pipelineRef:
    name: component-rbac-gen
  params:
    - name: URL
      value: https://github.com/kubebb/components/releases/download/kubebb-v0.0.1/kubebb-v0.0.1.tgz
    - name: COMPONENT_NAME
      value: kubebb
    - name: VERSION
      value: v0.0.1
```

当前流程已经跑通
<img width="1680" alt="image" src="https://github.com/kubebb/core/assets/20641704/59fa8798-b814-490d-ab32-7e89b4d6c454">
