### ISSUE TITLE
image override issue

### ISSUE THREAD

**Issue by 0xff-dev** [kubebb/core#185]
```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Repository
metadata:
  name: repo-override-image
  namespace: kubebb-system
spec:
  url: http://chartmuseum.default.svc.cluster.local:8080
  pullStategy:
    intervalSeconds: 120
    retry: 5
  imageOverride:
    - registry: ghcr.io
      newRegistry: localhost:5001
      pathOverride:
        path: helm
        newPath: ""
```

when use `ghcr.io/helm/abc:v1`. Expected actual `localhost:5001/abc:v1`, but got `localhost:5001/helm/abc:v1`
