### ISSUE TITLE
fully compatiable with original menus/component design

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#218]
## Scenarios

To be fully compatible with previous kubebb component design,we need :

- keep `parentOwnerReferences` in `menus` untile auto menus supported in `kubebb`  (this requirement comes from https://github.com/kubebb/core/discussions/200#discussioncomment-6633538)
- add a new CRD `Portal` in kubebb to configure `portal path`

For this new CRD `Portal`:
```yaml
type PortalSpec struct {
   Entry string
   Path string
}
```

## Sample
Take bc-apis as an example https://github.com/kubebb/components/blob/main/charts/bc-apis/templates/menus.yaml
1. Menus
only update apiVersion from `component.t7d.io/v1beta1` to `core.kubebb.k8s.com.cn/v1alpha1`

2. Component
replace [`component.yaml`](https://github.com/kubebb/components/blob/main/charts/bc-apis/templates/component.yaml) to `portal.yaml`

The `portal.yaml` would be :
```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Portal
metadata:
  name: bc
spec:
  entry: /bc-public/index.html
  path: /bc
```
