### ISSUE TITLE
Pain points when using helm directly 

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#30]
## 痛点
基于building-base服务或环境部署的痛点:
1. 需要手动定制portal
2. 需要手动修改服务镜像
3. RBAC和菜单定义与低代码服务耦合严重，使用组件的人无法自定义
4. 复杂组件内部需要依赖很多其他组件，依赖关系复杂
5. 集群镜像依赖管理复杂，环境变化时，无法有效的完成切换

### 解决组件参数定制

```yaml
name: repository-grafana.grafana
version: v1.0
# component exposed to other components for customization
# - api calls
# - resource management
self_expose:
  - name: grafana
    port: 3000
    protocol: http
    path: /
    type: NodePort
    nodePort: 30000
# depends: other components that this component depends on with desired customization
depends:
  - name: repository-kubebb-sample.ingress-nginx
    version: v1.0
    desired:
      - name: image
        type: update
        path: spec.template.spec.containers[0].image
        value: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      - name: portal_ingress
        operator: create
        value: portal.{{ .Release.Namespace }}.{{ .Values.portal.domain }}

```

### 解决依赖关系复杂

1. 基于[DOT语言规范](https://www.graphviz.org/pdf/dotguide.pdf)，添加组件定义以及和其他组件的依赖关系

```dot
digraph dependencies {
  rankdir=LR;
  
  subgraph cluster_self {
    "repository-kubebb.building-base" -> "menu"
    "repository-kubebb.building-base" -> "base_image" 
    "repository-kubebb.building-base" -> "ingress"
    "repository-kubebb.building-base" -> "tenant"
  }
  
  "repository-kubebb.building-base" -> "repository-bitnami.ingress-nginx"
  
  subgraph cluster_depends {
    "repository-bitnami.ingress-nginx"
  }
}
```

2. 通过gonum实时生成可视化图片

3. 基于依赖关系以及，组件`clusters_self`定义，灵活实现组件部署时的参数配置
