### ISSUE TITLE
add displayName in component

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#300]
To support 中文名称，we can add a annotation in Chart.yaml like 
```yaml
apiVersion: v2
name: core
annotations:
  core.kubebb.k8s.com.cn/displayname: "内核"
description: Kubebb Core provides core implementations on Component Lifecycle Management.Our design and development follows operator pattern which extends kubernetes APIs.
type: application
version: v0.1.12
appVersion: v0.1.4
icon: https://avatars.githubusercontent.com/u/85277200
keywords:
  - repository
  - helm
  - lifecycle-management
sources:
  - https://github.com/kubebb/core
maintainers:
  - name: bjwswang
    url: https://github.com/bjwswang
  - name: Abirdcfly
    url: https://github.com/Abirdcfly
  - name: 0xff-dev
    url: https://github.com/0xff-dev
```

When repository controller sync the components, we extract the annotation to component.
