### ISSUE TITLE
PipelineRun data in `Rating` status is lost.

### ISSUE THREAD

**Issue by 0xff-dev** [kubebb/core#350]
The pipelineruns data in `Rating` status is lost.

For pipelinerunes, expect

```yaml
  pipelineRuns:
    two-pipelines.only-helm-lint:
      actualWeight: 1
      conditions:
      - lastTransitionTime: "2023-08-23T05:41:16Z"
        message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
        reason: Succeeded
        status: "True"
        type: Succeeded
      expectWeight: 1
      pipelineName: only-helm-lint
      tasks:
      - conditions:
        - lastTransitionTime: "2023-08-23T05:41:16Z"
          message: All Steps have completed executing
          reason: Succeeded
          status: "True"
          type: Succeeded
        name: helm-lint
        taskRunName: two-pipelines.only-helm-lint-helm-lint
    two-pipelines.only-rback:
      actualWeight: 1
      conditions:
      - lastTransitionTime: "2023-08-23T05:43:26Z"
        message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
        reason: Succeeded
        status: "True"
        type: Succeeded
      expectWeight: 1
      pipelineName: only-rback
      tasks:
      - conditions:
        - lastTransitionTime: "2023-08-23T05:43:26Z"
          message: All Steps have completed executing
          reason: Succeeded
          status: "True"
          type: Succeeded
        name: rback
        taskRunName: two-pipelines.only-rback-rback
```

Now
```yaml
  pipelineRuns:
    reliability:
      pipelineName: kubebb-reliability
      pipelinerunName: rating-with-ai.reliability
    security:
      pipelineName: kubebb-security
      pipelinerunName: rating-with-ai.security
```
