### ISSUE TITLE
install ingress-nginx failed with componentplan

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#51]
## Bug

Failed to deploy ingress-nginx with kubebb componentplan but the charts works when using `helm install`

## How to reproduce

1. create a repo
```shell
kubectl apply -f repos/repo 
# https://github.com/kubebb/components/blob/main/repos/repository_kubebb.yaml
```
2. deploy with componentplan 
The component plan is :
```yaml
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: ingress-nginx
  namespace: kubebb-system
spec:
  approved: true
  name: ingress-nginx
  version: 4.7.0
  component:
    name: kubebb.ingress-nginx
    namespace: kubebb-system
```
