### ISSUE TITLE
versioned filter on component ignore

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#96]

**Comment by 0xff-dev** [comment]
一个chart包的基本信息如下
```yaml
  contour-operator:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.24.0
    created: "2023-05-16T09:23:19.034209148Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    deprecated: true
    description: DEPRECATED The Contour Operator extends the Kubernetes API to create,
      configure and manage instances of Contour on behalf of users.
    digest: a68e63c87d29cbda2a8a6f9d94da3c7c15edac251b4f6d63b7c25aad82f9720e
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/contour-operator/img/contour-operator-stack-220x234.png
    keywords:
    - contour
    - operator
    - ingress
    - envoy
    kubeVersion: '>= 1.21.0-0'
    name: contour-operator
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/contour-operator
    urls:
    - https://charts.bitnami.com/bitnami/contour-operator-4.2.1.tgz
    version: 4.2.1
```

1. 对于char包的名字不在过滤条件中的，保留全部版本

```yaml
  filter:
  - name: wordpress
    operation: ignore
```
这里只有对 wordpress 的过滤条件，但是接下来要处理 nginx，保留 nginx 的全部版本。

2. chart包的名字在过滤条件中，过滤条件为空，看 operator 如果是ignore忽略这个chart包，否则保留全部版本

```yaml
  filter:
  - name: wordpress
    operation: ignore
```


3. 如果 operator 是 keep

如果当前的wordpress有14.0.0(deprecated)， 15.0.0， 16.0.0(deprecated)， 17.0.0 四个版本

```yaml
filter:
- name: wordpress
  operator: keep
  deprecated: true
  versionedFilterCond:
      versionConstraint: ">= 16.0.0"
```
如果deprecated=true
上面的yaml表述的是：对于 wordpress 这个chart包，当他的版本 `>=16.0.0` 时候，就会保留这个版本
`经过筛选后留下 16.0.0, 17.0.0 两个版本`

如果deprecated=false
上面的yaml表述的是：对于 wordpress 这个chart包，当他的版本 `>=16.0.0` 且 该版本没有废弃的时候，会保留这个版本
`经过筛选后留下 17.0.0`

4. 如果 operator 是 ignore

如果当前的wordpress有14.0.0(deprecated)， 15.0.0， 16.0.0， 17.0.0 四个版本

```yaml
filter:
- name: wordpress
  operator: ignore
  deprecated: true
  versionedFilterCond:
      versionConstraint: ">= 16.0.0"
```

如果deprecated=true
上面的yaml表述的是：对于wordpress这个chart包，过滤掉 `>=16.0.0` 的版本。
`经过筛选后，留下 14.0.0, 15.0.0两个版本。`

如果depreacated=false
上述yaml表述的是：对于wordpress这个chart包，过滤掉 `>=16.0.0` 且已经废弃版本。
`经过筛选后，留下 15.0.0 版本。`
